#!/bin/bash
# In this game the hero moves from left to right
# The player rolls the dice and moves the number of spaces indicated by the
# dice and moves the number of spaces indicated by the dice two times
# Create a function for the terminal game that takes the current position of
# the hero (1-6) and return the new position

position=$1
roll=$2

#print to screen (roll X 2 ) + position
echo $(($roll * 2 + $position ))
