#!/bin/bash
# Write a program that finds the summation of every number from 1 to num
# The number will always be a positive integer greater than 0

n=$1
#1+2+3+4+5+6+7+8
num=0
for i in $(seq 1 $n)
do
	num=$(($num+$i))
done

echo "$num"
